swagger: '2.0'
info:
  title: CQS Helper API
  description: ''
  version: '1.0'
host: '@environmentVariables("cr8c9_CustomConnectorAzFunctionHostUrl")'
basePath: /
schemes:
  - https
consumes: []
produces: []
paths:
  /api/ListCallQueues:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: ListCallQueues
      operationId: ListCallQueues
      x-ms-visibility: important
      description: List teams call queues
  /api/UpdateCallQueueAgents:
    post:
      responses:
        default:
          description: default
          schema: {}
      summary: UpdateSelectCallQueueAgents
      operationId: UpdateSelectCallQueueAgents
      parameters:
        - name: Accept
          in: header
          required: false
          type: string
        - name: body
          in: body
          required: false
          schema:
            type: object
            properties:
              CQId:
                type: string
                description: CQId
              AgentsList:
                type: string
                description: AgentsList
      description: Updates the call queue agents
  /api/CsvInputParser:
    post:
      responses:
        default:
          description: default
          schema: {}
      summary: InvokeCSVParser
      operationId: InvokeCSVParser
      description: InvokeCSVParser
      x-ms-visibility: important
      parameters:
        - name: Content-Type
          in: header
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
        - name: body
          in: body
          required: false
          schema:
            type: object
            properties:
              filename:
                type: string
                description: filename
              filecontent:
                type: string
                description: filecontent
  /api/GetCallQueueById:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: GetCallQueueDetailsById
      operationId: GetCallQueueDetailsById
      parameters:
        - name: Identity
          in: query
          required: false
          type: string
      description: GetCallQueueDetailsById
  /api/TestAzFunction: {}
  /api/GetCallQueues:
    get:
      responses:
        default:
          description: default
          schema:
            type: array
            items:
              type: object
              properties:
                Name:
                  type: string
                  description: Name
                Identity:
                  type: string
                  description: Identity
                Agents:
                  type: array
                  items:
                    type: string
                  description: Agents
      summary: Get call queues details managed by current user
      operationId: GetCallQueuesForCurrentUser
      parameters: []
      description: Get call queues details managed by current user
definitions: {}
parameters: {}
responses: {}
securityDefinitions:
  oauth2-auth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://login.windows.net/common/oauth2/authorize
    tokenUrl: https://login.windows.net/common/oauth2/authorize
    scopes: {}
security:
  - oauth2-auth: []
tags: []
